### ISSUE TITLE
버그?

### ISSUE THREAD

**Issue by ilsubyeega** [devITae/EBSOCProgressViewer#6]
최근 미수강중으로 접근할 시 아래와 같은 오류를 발생합니다.
¯\_(ツ)_/¯

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.Runtime.InteropServices.COMException (0x80072EE5): The URL is invalid

   at Microsoft.VisualBasic.CompilerServices.LateBinding.InternalLateCall(Object o, Type objType, String name, Object[] args, String[] paramnames, Boolean[] CopyBack, Boolean IgnoreReturn)
   at Microsoft.VisualBasic.CompilerServices.NewLateBinding.LateCall(Object Instance, Type Type, String MemberName, Object[] Arguments, String[] ArgumentNames, Type[] TypeArguments, Boolean[] CopyBack, Boolean IgnoreReturn)
   at EBSOCStatus.Form1.CallNotEnrolled()
   at EBSOCStatus.Form1.lrnType_SelectedIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.ComboBox.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.ComboBox.WmReflectCommand(Message& m)
   at System.Windows.Forms.ComboBox.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll
----------------------------------------
EBSOCStatus
    Assembly Version: 2.3.1.0
    Win32 Version: 2.3.1.0
    CodeBase: file:///C:/bin/EBSOCPro2.31.exe
----------------------------------------
Microsoft.VisualBasic
    Assembly Version: 10.0.0.0
    Win32 Version: 14.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.VisualBasic/v4.0_10.0.0.0__b03f5f7f11d50a3a/Microsoft.VisualBasic.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4200.0 built by: NET48REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Runtime.Remoting
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Remoting/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Remoting.dll
----------------------------------------
Accessibility
    Assembly Version: 4.0.0.0
    Win32 Version: 4.8.4084.0 built by: NET48REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

**Comment by devITae** [comment]
#5 와 같은 오류로 예상됩니다. 
미수강중 리스트는 강의 페이지를 모두 파싱해오는 ~~(무식한)~~ 방식을 사용하기 때문에 서버가 불안정하거나 혹은 
로그인 세션이 만료되었거나 하는 등의 상황에서 발생합니다. (이 부분은 추후 업데이트에서 예외 처리를 해두도록 하겠습니다.)
혹시 다시 시도하더라도 같은 오류가 발생하는지 알 수 있을까요?

**Comment by ilsubyeega** [comment]
> #5 와 같은 오류로 예상됩니다.
> 미수강중 리스트는 강의 페이지를 모두 파싱해오는 ~(무식한)~ 방식을 사용하기 때문에 서버가 불안정하거나 혹은
> 로그인 세션이 만료되었거나 하는 등의 상황에서 발생합니다. (이 부분은 추후 업데이트에서 예외 처리를 해두도록 하겠습니다.)
> 혹시 다시 시도하더라도 같은 오류가 발생하는지 알 수 있을까요?

몇일 전부터 계속 지속되는데 예상되는 이유는 클래스가 삭제된것 같습니다.
이전에 클론해서 시도해볼려고 했으나 어떤 문제인지 IndexOutOfRangeException 예외가 나오네요

**Comment by devITae** [comment]
인터넷으로 클래스를 접속할 때, 강의 목록이 바로 안뜨는 경우에 생기는 오류를 수정한 테스트 버전입니다.
혹시 오류가 뜨는 지 확인 부탁드립니다.
https://github.com/devITae/EBSOCProgressViewer/blob/master/img/beta/2.4test2.exe

**Comment by ilsubyeega** [comment]
> 인터넷으로 클래스를 접속할 때, 강의 목록이 바로 안뜨는 경우에 생기는 오류를 수정한 테스트 버전입니다.
> 혹시 오류가 뜨는 지 확인 부탁드립니다.
> https://github.com/devITae/EBSOCProgressViewer/blob/master/img/beta/2.4test2.exe

![image](https://user-images.githubusercontent.com/37479424/93470774-6285c580-f92d-11ea-861c-07c5bdcdaab2.png)
아쉽네요 ㅠㅠ

**Comment by devITae** [comment]
아... 마음같아선 제가 직접이라도 해서 찾아내고 싶은데 이것만으로는 오류를 캐낼 수가 없어서 아쉽네요..
혹시 나중에 시간되시면 원격으로 디버깅 해봐도 될까요??

**Comment by ilsubyeega** [comment]
> 아... 마음같아선 제가 직접이라도 해서 찾아내고 싶은데 이것만으로는 오류를 캐낼 수가 없어서 아쉽네요..
> 혹시 나중에 시간되시면 원격으로 디버깅 해봐도 될까요??

당연합니다! 카카오톡 sob@kakao.com 또는 mediamc3 로 추후 연락 부탁드립니다

**Comment by devITae** [comment]
2.4 업데이트로 수정되었습니다. 도와주셔서 감사합니다!
